### PR TITLE
Release v0.8.11

### PR DESCRIPTION
**Pull request by gwicke**

### CODE REVIEW

**Comment by gwicke** [comment]
Self-merge, as trivial.

**Comment by d00rman** [comment]
@gwicke please tag the release

**Comment by gwicke** [comment]
@d00rman, it is tagged: https://github.com/gwicke/restbase-mod-table-cassandra/releases/tag/v0.8.11

**Comment by d00rman** [comment]
> The issue seems to be that tags aren't automatically transferred as part of a PR. Are you simply pushing the tag to the wikimedia repo before CR?

First I merge the PR, then do locally:

```
git fetch --all && git rebase upstream/master && git push && npm publish && git tag -a vX.X.X -m 'pkg-name vX.X.X release' && git push upstream vX.X.X
```

where my fork's remote name is *origin* and wikimedia's is named *upstream*.

**Comment by gwicke** [comment]
I normally do the tagging along with the commit & push it to my repo. I pushed those tags to wikimedia as well, but the workflow isn't ideal, imho.

**Pull request merged**
