### PR TITLE
Update to a newer cassandra driver and use built-in promise support

### PR DESCRIPTION
**Pull request by Pchelolo**
The new driver version is released and it has built-in promise support - let's use it!

I've measured the performance locally a bit, but no significant difference was found, need to run a dump in staging to get more data.

Bug: https://phabricator.wikimedia.org/T156441

### CODE REVIEW

**Comment by eevans** [comment]
@d00rman said:
> Nevertheless, because we are switching to a different syntax (and use different underlying methods), we should carefully test it in staging.

Yup!

@Pchelolo does it make sense to likewise convert the uses under `maintenance/`?

Otherwise, LGTM :+1:

**Comment by d00rman** [comment]
> @Pchelolo does it make sense to likewise convert the uses under maintenance/?

It would be great to convert those too as we can then use them to "test a bit" before going full-on into the replacement in RB.

**Comment by d00rman** [comment]
:+1: Test next week?

**Comment by Pchelolo** [comment]
@d00rman Yea, after deploying the more urgent matters

**Comment by Pchelolo** [comment]
Done. Updated the maintenance scripts as well (not tested though)

**Comment by Pchelolo** [comment]
Published as restbase-mod-table-cassandra@0.11.0

**Pull request merged**
